
[Generation]
	#Whether or not sea serpents can break weak blocks in their way
	"Sea Serpent Griefing" = true
	#1 out of this number chance per chunk for generation
	#Range: 1 ~ 1000
	"Spawn Centaur Chance" = 50
	#1 out of this number chance per chunk for generation
	#Range: 1 ~ 10000
	"Spawn Sea Serpent Chance" = 250
	#How far away stymphalian birds will consider other birds to be in the same flock.
	#Range: 1 ~ 10000
	"Stymphalian Bird Flock Length" = 40
	#True if stymphalian birds are allowed to spawn
	"Spawn Stymphalian Birds" = true
	#1 out of this number chance per chunk for generation
	#Range: 1 ~ 10000
	"Spawn Stymhphalian Bird Chance" = 100

